### ISSUE TITLE
Publish on crates.io?

### ISSUE THREAD

**Issue by okdistribute** [donbright/earcutr#2]
Hi! We're using this package as part of our rust implementation of a new format for packing OSM data. Do you have any intention of publishing this on the crates.io website? Otherwise, it seems like I'll have to add your git repository as a submodule etc, which isn't ideal.

Thanks @donbright !

**Comment by Maximkaaa** [comment]
Yes, this would be a very useful crate. @donbright would you like a PR with some docs to make it more suitable for crates.io and docs.rs?

**Comment by frewsxcv** [comment]
Hi! Been following this GitHub Issue since it was opened. I'm working on a project that utilizes this (wonderful) crate. @donbright is it okay if I publish this to crates.io on a fork? I'll of course still attribute you in the copyright, and happily give you ownership of the crates.io name if you decide you want it. Thanks so much for writing this!

**Comment by okdistribute** [comment]
hehe thanks @frewsxcv .. i was thinking about doing the same thing!

**Comment by frewsxcv** [comment]
Forked and published: https://github.com/frewsxcv/earcutr https://crates.io/crates/earcutr

**Comment by donbright** [comment]
yeah uhm go for it? 

long story. 

thanks
